version: "3.7"
services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./init-test-db/init.sql:/docker-entrypoint-initdb.d/init-db.sql
  city-list-app:
    image: citylist
    container_name: city-list-app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      DB_SERVER_NAME: "postgres"
      DB_PORT: 5432
      DB_NAME: "kuehnenagel"
      DB_USERNAME: "test"
      DB_PASSWORD: "test"
